# Generated by Django 4.0.4 on 2022-05-19 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0007_alter_appointment_id_alter_department_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='hospital.doctor'),
            preserve_default=False,
        ),
    ]
