# Generated by Django 4.0.4 on 2022-05-26 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0008_appointment_doctor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=20)),
                ('blog', models.CharField(max_length=20)),
                ('author', models.CharField(max_length=20)),
                ('date', models.TimeField(auto_now=True)),
            ],
        ),
    ]
